sudo: required

language: generic

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - TAG=unstable

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=cassinyio/redis
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO

